name: Build Community Profiles

on:
  repository_dispatch:
    types: [build]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RECIPE_ENGINE: ${{ secrets.RECIPE_ENGINE }}
      EDM_DATA: ${{ secrets.EDM_DATA }}
      API_TOKEN: ${{ secrets.API_TOKEN }}
      BUILD_ENGINE: ${{ secrets.BUILD_ENGINE }}

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y postgresql-client-10
        
    - name: Run Build
      working-directory: cdprofiles_build
      run: |
        ./build.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: output
        path: output/cd_profiles.csv

    - name: Commit files
      run: |
          DATE=$(date)
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull
          git add output/cd_profiles.csv
          git commit -m "🎉 Rerun and Update Community Profiles Data $DATE" -a
          
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
