name: Publish Community Profiles Data
on:
  issue_comment:
    types: [created]
  
jobs:
  publish:
    runs-on: ubuntu-latest
    if: >- 
      contains(github.event.issue.title, '[publish]') && 
      contains(github.event.comment.body, '[publish]') && 
      (
        github.event.comment.author_association == 'MEMBER'
      )
    runs-on: self-hosted
    env:
      AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies ...
      run: |
        curl -O https://dl.min.io/client/mc/release/linux-amd64/mc
        chmod +x mc
        sudo mv ./mc /usr/bin
        mc alias set spaces $AWS_S3_ENDPOINT $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY --api S3v4

    - name: Publish
      id: publish
      run: ./publish.sh
                
    - name: Success Message
      if: success()
      uses: peter-evans/create-or-update-comment@v1
      with:
        comment-id: ${{ github.event.comment.id }}
        body: |
          ## Publish Complete!
          for more details, check https://github.com/NYCPlanning/db-community-profiles/actions/runs/${{ github.run_id }}
        reactions: hooray