name: Building Community Profiles

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '**.csv'
jobs:
  test:
    runs-on: ubuntu-latest
    if: contains(github, '[test]')
    env:
      RECIPE_ENGINE: ${{ secrets.RECIPE_ENGINE }}
      EDM_DATA: ${{ secrets.EDM_DATA }}
      API_TOKEN: ${{ secrets.API_TOKEN }}
      BUILD_ENGINE: postgresql://postgres:postgres@localhost:5432/postgres

    services:
      postgres:
        image: postgis/postgis:11-3.0-alpine
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y postgresql-client-10
        
    - name: Run Build
      working-directory: cdprofiles_build
      run: |
        ./build.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: output
        path: output/cd_profiles.csv

